package com.tanghui.dev.idea.plugin.devserver.ui.dialog.upload;

import com.intellij.icons.AllIcons;
import com.intellij.openapi.fileChooser.FileChooser;
import com.intellij.openapi.fileChooser.FileChooserDescriptor;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.vfs.LocalFileSystem;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.ui.components.JBPanel;
import com.intellij.ui.components.JBRadioButton;
import com.intellij.ui.components.fields.ExtendableTextComponent;
import com.intellij.ui.components.fields.ExtendableTextField;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.util.ui.JBUI;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.tanghui.dev.idea.plugin.devserver.data.model.FileTransferModel;
import com.tanghui.dev.idea.plugin.devserver.data.model.ServerHostModel;
import com.tanghui.dev.idea.plugin.devserver.task.FileTransferCallback;
import lombok.Getter;
import org.apache.commons.lang3.StringUtils;

import javax.swing.JComponent;
import java.awt.*;

/**
 * @BelongsPackage: com.tanghuidev.idea.plugin.connect.ui.dialog
 * @Author: 唐煇
 * @CreateTime: 2026-01-20-13:43
 * @Description: 描述类的主要功能和用途。
 * @Version: v1.0
 */
@Getter
public class UploadFileAction {
    private JBPanel<?> root;
    private JBRadioButton currentFile;
    private JBRadioButton otherFile;
    private JBPanel<?> uploadFile;
    private ExtendableTextField fileTextField;
    private final Project project;
    private final ServerHostModel serverHostModel;
    private final FileTransferModel fileTransferModel;
    private final FileTransferCallback fileTransferCallback;

    public UploadFileAction(Project project, ServerHostModel serverHostModel, FileTransferModel fileTransferModel, FileTransferCallback fileTransferCallback) {
        this.project = project;
        this.serverHostModel = serverHostModel;
        this.fileTransferModel = fileTransferModel;
        this.fileTransferCallback = fileTransferCallback;

        $$$setupUI$$$();
        this.currentFile.setSelected(true);
        this.otherFile.setSelected(false);
        this.uploadFile.setVisible(false);
        this.currentFile.addActionListener(e -> {
            if (currentFile.isSelected()) {
                otherFile.setSelected(false);
                uploadFile.setVisible(false);
            }
        });

        this.otherFile.addActionListener(e -> {
            if (otherFile.isSelected()) {
                currentFile.setSelected(false);
                uploadFile.setVisible(true);
            }
        });
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JBPanel();
        root.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        root.setMaximumSize(JBUI.size(600, 90));
        root.setMinimumSize(JBUI.size(600, 90));
        root.setPreferredSize(JBUI.size(600, 90));
        final JBPanel panel1 = new JBPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setMaximumSize(JBUI.size(2147483647, 40));
        panel1.setMinimumSize(JBUI.size(24, 40));
        panel1.setPreferredSize(JBUI.size(24, 40));
        CellConstraints cc = new CellConstraints();
        root.add(panel1, cc.xy(1, 1));
        final JBPanel panel2 = new JBPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 30, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        currentFile = new JBRadioButton();
        currentFile.setText("当前文件");
        panel2.add(currentFile, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel3 = new JBPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 30, 0, 0), -1, -1));
        panel1.add(panel3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        otherFile = new JBRadioButton();
        otherFile.setText("其他文件");
        panel3.add(otherFile, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        uploadFile = new JBPanel();
        uploadFile.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        uploadFile.setMaximumSize(JBUI.size(2147483647, 40));
        uploadFile.setMinimumSize(JBUI.size(24, 40));
        uploadFile.setPreferredSize(JBUI.size(24, 40));
        root.add(uploadFile, cc.xy(1, 3));
        uploadFile.add(fileTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    private void createUIComponents() {
        this.fileTextField = new ExtendableTextField();
        // 选择文件按钮
        ExtendableTextComponent.Extension chooseFileButton =
                ExtendableTextComponent.Extension.create(
                        AllIcons.Nodes.Folder,          // 图标
                        AllIcons.Nodes.Folder,          // hover 图标
                        "选择文件",
                        () -> {
                            FileChooserDescriptor descriptor =
                                    new FileChooserDescriptor(true, false, false, false, false, false);
                            VirtualFile file;
                            if (StringUtils.isNotBlank(fileTextField.getText())) {
                                VirtualFile defaultDir =
                                        LocalFileSystem.getInstance()
                                                .findFileByPath(fileTextField.getText());
                                file = FileChooser.chooseFile(descriptor, null, defaultDir);
                            } else {
                                file = FileChooser.chooseFile(descriptor, null, null);
                            }
                            if (file != null) {
                                fileTextField.setText(file.getPath());
                            }
                        }
                );
        this.fileTextField.addExtension(chooseFileButton);
    }
}
