package com.tanghui.dev.idea.plugin.devserver.transfer.ui;

import com.intellij.openapi.project.Project;
import com.intellij.ui.JBColor;
import com.intellij.ui.components.JBPanel;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.components.JBTabbedPane;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.util.ui.JBUI;
import lombok.Getter;
import org.apache.commons.collections.CollectionUtils;

import javax.swing.*;
import javax.swing.plaf.basic.BasicScrollBarUI;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @BelongsPackage: com.tanghui.dev.idea.plugin.devserver.transfer.ui
 * @Author: 唐煇
 * @CreateTime: 2025-12-10-11:42
 * @Description: 多文件传输ui。
 * @Version: v1.0
 */
@Getter
public class MultipleFileTransfer {
    // 根组件
    private JBPanel<?> root;
    // tab 组件
    private JBTabbedPane uploadTabbedPane;

    private JBScrollPane uploadScrollPane;
    // 单个文件传输列表
    private List<FileTransfer> fileTransferList = new ArrayList<>();

    /**
     * 当前打开项目
     * */
    private final Project project;


    public MultipleFileTransfer(Project project, List<FileTransfer> fileTransferList) {
        this.fileTransferList = fileTransferList;
        this.project = project;
        updateTabbedPane();
    }

    public MultipleFileTransfer(Project project) {
        this.project = project;
        updateTabbedPane();
    }

    public void addFileTransfer(FileTransfer fileTransfer) {
        this.fileTransferList.add(fileTransfer);
        updateTabbedPane();
    }

    private void updateTabbedPane() {
        this.uploadScrollPane.setHorizontalScrollBarPolicy(JBScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        JScrollBar vBar = this.uploadScrollPane.getVerticalScrollBar();
        vBar.setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.trackColor = new JBColor(new Color(29, 32, 33), new Color(29, 32, 33));      // 滚动条颜色
                this.thumbColor = new JBColor(new Color(80, 73, 69), new Color(80, 73, 69));      // 背景轨道颜色
            }

            @Override
            public Dimension getPreferredSize(JComponent c) {
                return JBUI.size(8, super.getPreferredSize(c).height); // 宽度=8px
            }
        });
        this.uploadScrollPane.getVerticalScrollBar().setUnitIncrement(20);
        if (CollectionUtils.isNotEmpty(this.fileTransferList)) {
            SwingUtilities.invokeLater(() -> {
                for (FileTransfer fileTransfer : this.fileTransferList) {
                    String text = fileTransfer.getServerTextField().getText();
                    this.uploadTabbedPane.add(text, fileTransfer.getRoot());
                }
                this.uploadTabbedPane.updateUI();
            });
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JBPanel();
        root.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JBPanel panel1 = new JBPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        root.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        uploadScrollPane = new JBScrollPane();
        panel1.add(uploadScrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JBPanel panel2 = new JBPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        uploadScrollPane.setViewportView(panel2);
        uploadTabbedPane = new JBTabbedPane();
        panel2.add(uploadTabbedPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
