package com.tanghui.dev.idea.plugin.devserver.ui.dialog.execute;

import com.alibaba.fastjson.JSONObject;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.project.Project;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBPanel;
import com.intellij.ui.components.JBTextField;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.tanghui.dev.idea.plugin.devserver.data.model.OperateEnum;
import com.tanghui.dev.idea.plugin.devserver.ui.server.RemoteServer;
import lombok.Getter;

import javax.swing.JComponent;
import java.awt.*;

/**
 * @BelongsPackage: com.tanghuidev.idea.plugin.connect.ui.dialog
 * @Author: 唐煇
 * @CreateTime: 2026-01-20-16:53
 * @Description: 描述类的主要功能和用途。
 * @Version: v1.0
 */
@Getter
public class EditCommand {
    private JBPanel<?> root;
    private JBTextField titleTextField;
    private JBTextField userTextField;
    private JBTextField directoryTextField;
    private JBTextField serverGroupBy;

    private final Project project;
    private final RemoteServer command;
    private final OperateEnum type; // 新增，修改，删除

    public EditCommand(Project project, RemoteServer command, OperateEnum type) {
        this.project = project;
        this.command = command;
        this.type = type;
        initComponents();
    }

    private void initComponents() {
        ApplicationManager.getApplication().invokeAndWait(() -> {
            // 获取选中的执行命令
            JSONObject selectedCommandJson = command.getSelectedCommandJson(command.getLastLeft().getServerTree(), command.getLastRight().getExecuteLeft().getCommandTree());
            if (selectedCommandJson == null) {
                return;
            }
            serverGroupBy.setText(selectedCommandJson.getString("path"));
            if (OperateEnum.UPDATE.equals(this.type) || OperateEnum.DELETE.equals(this.type)) {
                titleTextField.setText(selectedCommandJson.getString("title"));
                userTextField.setText(selectedCommandJson.getString("user"));
                directoryTextField.setText(selectedCommandJson.getString("directory"));
            }
            if (OperateEnum.DELETE.equals(this.type)) {
                titleTextField.setEditable(false);
                userTextField.setEditable(false);
                directoryTextField.setEditable(false);
                serverGroupBy.setEditable(false);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JBPanel();
        root.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        root.setMaximumSize(new Dimension(400, 2147483647));
        root.setMinimumSize(new Dimension(400, 181));
        root.setPreferredSize(new Dimension(400, 181));
        final JBPanel panel1 = new JBPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setMaximumSize(new Dimension(2147483647, 40));
        panel1.setMinimumSize(new Dimension(24, 40));
        panel1.setPreferredSize(new Dimension(24, 40));
        CellConstraints cc = new CellConstraints();
        root.add(panel1, cc.xy(1, 1));
        final JBPanel panel2 = new JBPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setMaximumSize(new Dimension(80, 2147483647));
        panel2.setMinimumSize(new Dimension(80, 24));
        panel2.setPreferredSize(new Dimension(80, 24));
        panel1.add(panel2, BorderLayout.WEST);
        final JBLabel label1 = new JBLabel();
        label1.setText("命令标题");
        panel2.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel3 = new JBPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, BorderLayout.CENTER);
        titleTextField = new JBTextField();
        panel3.add(titleTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JBPanel panel4 = new JBPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel4.setMaximumSize(new Dimension(2147483647, 40));
        panel4.setMinimumSize(new Dimension(24, 40));
        panel4.setPreferredSize(new Dimension(24, 40));
        root.add(panel4, cc.xy(1, 3));
        final JBPanel panel5 = new JBPanel();
        panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel5.setMaximumSize(new Dimension(80, 2147483647));
        panel5.setMinimumSize(new Dimension(80, 24));
        panel5.setPreferredSize(new Dimension(80, 24));
        panel4.add(panel5, BorderLayout.WEST);
        final JBLabel label2 = new JBLabel();
        label2.setText("执行用户");
        panel5.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel6 = new JBPanel();
        panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel4.add(panel6, BorderLayout.CENTER);
        userTextField = new JBTextField();
        panel6.add(userTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JBPanel panel7 = new JBPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        panel7.setMaximumSize(new Dimension(2147483647, 40));
        panel7.setMinimumSize(new Dimension(24, 40));
        panel7.setPreferredSize(new Dimension(24, 40));
        root.add(panel7, cc.xy(1, 5));
        final JBPanel panel8 = new JBPanel();
        panel8.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel8.setMaximumSize(new Dimension(80, 2147483647));
        panel8.setMinimumSize(new Dimension(80, 24));
        panel8.setPreferredSize(new Dimension(80, 24));
        panel7.add(panel8, BorderLayout.WEST);
        final JBLabel label3 = new JBLabel();
        label3.setText("执行目录");
        panel8.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel9 = new JBPanel();
        panel9.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel7.add(panel9, BorderLayout.CENTER);
        directoryTextField = new JBTextField();
        panel9.add(directoryTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JBPanel panel10 = new JBPanel();
        panel10.setLayout(new BorderLayout(0, 0));
        panel10.setMaximumSize(new Dimension(2147483647, 40));
        panel10.setMinimumSize(new Dimension(24, 40));
        panel10.setPreferredSize(new Dimension(24, 40));
        root.add(panel10, cc.xy(1, 7));
        final JBPanel panel11 = new JBPanel();
        panel11.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel11.setMaximumSize(new Dimension(80, 2147483647));
        panel11.setMinimumSize(new Dimension(80, 24));
        panel11.setPreferredSize(new Dimension(80, 24));
        panel10.add(panel11, BorderLayout.WEST);
        final JBLabel label4 = new JBLabel();
        label4.setText("分组");
        panel11.add(label4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel12 = new JBPanel();
        panel12.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel10.add(panel12, BorderLayout.CENTER);
        serverGroupBy = new JBTextField();
        panel12.add(serverGroupBy, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
