package com.tanghui.dev.idea.plugin.devserver.ui.dialog.connectserver;

import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.ComboBox;
import com.intellij.ui.ColoredListCellRenderer;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBPanel;
import com.intellij.ui.components.JBPasswordField;
import com.intellij.ui.components.JBTextField;
import com.intellij.ui.components.fields.IntegerField;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.util.ui.JBUI;
import com.tanghui.dev.idea.plugin.devserver.DevServerBundle;
import com.tanghui.dev.idea.plugin.devserver.data.model.OperateEnum;
import com.tanghui.dev.idea.plugin.devserver.data.model.OsType;
import com.tanghui.dev.idea.plugin.devserver.data.model.ServerHostModel;
import lombok.Getter;
import lombok.Setter;

import javax.swing.*;
import java.awt.*;

/**
 * @BelongsPackage: com.tanghui.dev.idea.plugin.devserver.ui.dialog.connectserver
 * @Author: 唐煇
 * @CreateTime: 2025-12-22-09:35
 * @Description: 描述类的主要功能和用途。
 * @Version: v1.0
 */
@Setter
@Getter
public class ConnectServer {

    private JBPanel<?> root;

    private IntegerField serverPort;

    private JBTextField serverUser;

    private JBPasswordField serverPassword;

    private JBTextField serverGroupBy;

    private JBTextField describe;

    private JBLabel feedback;
    private JBTextField serverHost;
    // 系统类型
    private ComboBox<OsType> osType;

    private final Project project;
    private final OperateEnum operate;
    private final ServerHostModel serverHostModel;

    public ConnectServer(Project project,
                         OperateEnum operate,
                         ServerHostModel serverHostModel) {
        this.project = project;
        this.operate = operate;
        this.serverHostModel = serverHostModel;
        initServerGroupBy();
        initData();
    }

    private void initData() {
        if (OperateEnum.ADD.equals(operate)) {
            return;
        }
        this.serverHost.setText(this.serverHostModel.getHost());
        this.serverPort.setText(this.serverHostModel.getPort().toString());
        this.serverUser.setText(this.serverHostModel.getUserName());
        this.serverPassword.setText(this.serverHostModel.getPassword());
        this.serverGroupBy.setText(this.serverHostModel.getServerGroupBy());
        String osTypeName = this.serverHostModel.getOsType();
        OsType osType = OsType.fromDisplayName(osTypeName);
        this.osType.setSelectedItem(osType);
        this.describe.setText(this.serverHostModel.getEnvironment());

        if (OperateEnum.DELETE.equals(operate)) {
            this.serverHost.setEditable(false);
            this.serverPort.setEditable(false);
            this.serverUser.setEditable(false);
            this.serverPassword.setEditable(false);
            this.serverGroupBy.setEditable(false);
            this.describe.setEditable(false);
            this.osType.setEnabled(false);
        }
    }

    private void initServerGroupBy() {
        this.serverGroupBy.setText(this.serverHostModel.getServerGroupBy());
        this.serverGroupBy.updateUI();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JBPanel();
        root.setLayout(new BorderLayout(0, 0));
        root.setMaximumSize(JBUI.size(400, 340));
        root.setMinimumSize(JBUI.size(400, 340));
        root.setPreferredSize(JBUI.size(400, 340));
        final JBPanel panel1 = new JBPanel();
        panel1.setLayout(new GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setMaximumSize(JBUI.size(2147483647, 260));
        panel1.setMinimumSize(JBUI.size(24, 260));
        panel1.setPreferredSize(JBUI.size(24, 260));
        root.add(panel1, BorderLayout.NORTH);
        final JBPanel panel2 = new JBPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JBPanel panel3 = new JBPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3, BorderLayout.CENTER);
        final JBPanel panel4 = new JBPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel4.setMaximumSize(JBUI.size(260, 2147483647));
        panel4.setMinimumSize(JBUI.size(260, 24));
        panel4.setPreferredSize(JBUI.size(260, 24));
        panel3.add(panel4, BorderLayout.WEST);
        final JBPanel panel5 = new JBPanel();
        panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel5.setMaximumSize(JBUI.size(70, 2147483647));
        panel5.setMinimumSize(JBUI.size(70, 24));
        panel5.setPreferredSize(JBUI.size(70, 24));
        panel4.add(panel5, BorderLayout.WEST);
        final JBLabel label1 = new JBLabel();
        label1.setText(DevServerBundle.INSTANCE.message("host"));
        panel5.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel6 = new JBPanel();
        panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel4.add(panel6, BorderLayout.CENTER);
        serverHost = new JBTextField();
        panel6.add(serverHost, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, JBUI.size(150, -1), null, 0, false));
        final JBPanel panel7 = new JBPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        panel3.add(panel7, BorderLayout.CENTER);
        final JBPanel panel8 = new JBPanel();
        panel8.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel8.setMaximumSize(JBUI.size(70, 2147483647));
        panel8.setMinimumSize(JBUI.size(70, 24));
        panel8.setPreferredSize(JBUI.size(70, 24));
        panel7.add(panel8, BorderLayout.WEST);
        final JBLabel label2 = new JBLabel();
        label2.setText(DevServerBundle.INSTANCE.message("port"));
        panel8.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel9 = new JBPanel();
        panel9.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel7.add(panel9, BorderLayout.CENTER);
        serverPort = new IntegerField(null, 1, 99999);
        serverPort.setDefaultValue(22);
        panel9.add(serverPort, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        final JBPanel panelOsType = new JBPanel();
        panelOsType.setLayout(new BorderLayout(0, 0));
        panel1.add(panelOsType, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JBPanel panelOsTypeName = new JBPanel();
        panelOsTypeName.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelOsTypeName.setMaximumSize(JBUI.size(70, 2147483647));
        panelOsTypeName.setMinimumSize(JBUI.size(70, 24));
        panelOsTypeName.setPreferredSize(JBUI.size(70, 24));
        panelOsType.add(panelOsTypeName, BorderLayout.WEST);
        final JBLabel panelOsTypeNameLabel = new JBLabel();
        panelOsTypeNameLabel.setText(DevServerBundle.INSTANCE.message("server.type"));
        panelOsTypeName.add(panelOsTypeNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panelOsTypeValue = new JBPanel();
        panelOsTypeValue.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelOsType.add(panelOsTypeValue, BorderLayout.CENTER);
        osType = new ComboBox<>(OsType.values());
        osType.setRenderer(new ColoredListCellRenderer<>() {
            @Override
            protected void customizeCellRenderer(
                    JList<? extends OsType> list,
                    OsType value,
                    int index,
                    boolean selected,
                    boolean hasFocus
            ) {
                if (value == null) return;
                setIcon(value.getIcon());
                append(value.getDisplayName());
            }
        });
        panelOsTypeValue.add(osType, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, JBUI.size(150, -1), null, 0, false));

        final JBPanel panel10 = new JBPanel();
        panel10.setLayout(new BorderLayout(0, 0));
        panel1.add(panel10, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JBPanel panel11 = new JBPanel();
        panel11.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel11.setMaximumSize(JBUI.size(70, 2147483647));
        panel11.setMinimumSize(JBUI.size(70, 24));
        panel11.setPreferredSize(JBUI.size(70, 24));
        panel10.add(panel11, BorderLayout.WEST);
        final JBLabel label3 = new JBLabel();
        label3.setText(DevServerBundle.INSTANCE.message("user"));
        panel11.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel12 = new JBPanel();
        panel12.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel10.add(panel12, BorderLayout.CENTER);
        serverUser = new JBTextField();
        panel12.add(serverUser, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, JBUI.size(150, -1), null, 0, false));
        final JBPanel panel13 = new JBPanel();
        panel13.setLayout(new BorderLayout(0, 0));
        panel1.add(panel13, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JBPanel panel14 = new JBPanel();
        panel14.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel14.setMaximumSize(JBUI.size(70, 2147483647));
        panel14.setMinimumSize(JBUI.size(70, 24));
        panel14.setPreferredSize(JBUI.size(70, 24));
        panel13.add(panel14, BorderLayout.WEST);
        final JBLabel label4 = new JBLabel();
        label4.setText(DevServerBundle.INSTANCE.message("password"));
        panel14.add(label4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel15 = new JBPanel();
        panel15.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel13.add(panel15, BorderLayout.CENTER);
        serverPassword = new JBPasswordField();
        panel15.add(serverPassword, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, JBUI.size(150, -1), null, 0, false));
        final JBPanel panel16 = new JBPanel();
        panel16.setLayout(new BorderLayout(0, 0));
        panel1.add(panel16, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JBPanel panel17 = new JBPanel();
        panel17.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel17.setMaximumSize(JBUI.size(70, 2147483647));
        panel17.setMinimumSize(JBUI.size(70, 24));
        panel17.setPreferredSize(JBUI.size(70, 24));
        panel16.add(panel17, BorderLayout.WEST);
        final JBLabel label5 = new JBLabel();
        label5.setText(DevServerBundle.INSTANCE.message("group"));
        panel17.add(label5, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel18 = new JBPanel();
        panel18.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel16.add(panel18, BorderLayout.CENTER);
        serverGroupBy = new JBTextField();
        panel18.add(serverGroupBy, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, JBUI.size(150, -1), null, 0, false));
        final JBPanel panel19 = new JBPanel();
        panel19.setLayout(new BorderLayout(0, 0));
        panel1.add(panel19, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JBPanel panel20 = new JBPanel();
        panel20.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel20.setMaximumSize(JBUI.size(70, 2147483647));
        panel20.setMinimumSize(JBUI.size(70, 24));
        panel20.setPreferredSize(JBUI.size(70, 24));
        panel19.add(panel20, BorderLayout.WEST);
        final JBLabel label6 = new JBLabel();
        label6.setText(DevServerBundle.INSTANCE.message("describe"));
        panel20.add(label6, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel21 = new JBPanel();
        panel21.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel19.add(panel21, BorderLayout.CENTER);
        describe = new JBTextField();
        panel21.add(describe, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, JBUI.size(150, -1), null, 0, false));
        final JBPanel panel22 = new JBPanel();
        panel22.setLayout(new GridLayoutManager(1, 1, new Insets(0, 20, 0, 0), -1, -1));
        root.add(panel22, BorderLayout.CENTER);
        final JBPanel panel23 = new JBPanel();
        panel23.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel22.add(panel23, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        feedback = new JBLabel();
        feedback.setText("");
        panel23.add(feedback, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
