package com.tanghui.dev.idea.plugin.devserver.ui;


import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.intellij.openapi.actionSystem.ActionPlaces;
import com.intellij.openapi.actionSystem.ActionToolbar;
import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.project.Project;
import com.intellij.ui.components.JBPanel;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.table.JBTable;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.util.ui.JBUI;
import com.tanghui.dev.idea.plugin.devserver.ui.model.DevServerTableModel;
import com.tanghui.dev.idea.plugin.devserver.ui.renderer.TableViewRenderer;
import com.tanghui.dev.idea.plugin.devserver.utils.CollectionUtil;
import lombok.Getter;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;

import javax.swing.JComponent;
import javax.swing.table.TableCellRenderer;
import java.awt.*;
import java.util.Collections;
import java.util.List;
import java.util.Vector;

import static com.tanghui.dev.idea.plugin.devserver.utils.DevServerUtil.createActionToolBar;

/**
 * @BelongsPackage: com.tanghuidev.idea.plugin.ui
 * @Author: 唐煇
 * @CreateTime: 2025-09-16-09:49
 * @Description: DevServer自定义表格组件。
 * @Version: v1.0
 */
@Setter
@Getter
public class DevServerTable {
    // 根组件容器
    private JBPanel<?> root;
    // 头部组件
    private JBPanel<?> headComponent;
    // 表格组件
    private JBPanel<?> tableComponent;
    // 表格
    private JBTable devServerTableComponent;
    // 项目
    private Project project;


    public DevServerTable(@NotNull Project project, List<AnAction> actions) {
        this.project = project;
        if (headComponent != null && CollectionUtil.isNotEmpty(actions)) {
            initToolbar(actions);
        }
        // 设置行高
        devServerTableComponent.setRowHeight(35); // 每行高度 35 像素
        devServerTableComponent.setDefaultRenderer(Object.class, new TableViewRenderer());
        float scale = JBUI.pixScale();
        Dimension preferredSize = new Dimension(0, (int) (30 * scale));
        headComponent.setPreferredSize(preferredSize);
    }

    public DevServerTable(@NotNull Project project) {
        this(project, Collections.emptyList());
    }

    /**
     * 初始化操作栏
     * */
    public void initToolbar(List<AnAction> actions) {
        ActionToolbar actionToolBar = createActionToolBar(ActionPlaces.TOOLBAR, true, actions);
        headComponent.add(actionToolBar.getComponent());
        headComponent.setVisible(true);
    }

    /**
     * 设置表格模型
     * @param columnNames 表头
     * @param list 列表数据
     * */
    public void setTableModel(String[] columnNames, JSONArray list, @NotNull Boolean isEditable) {
        DevServerTableModel modelFile = getDefaultTableModel(columnNames, list, isEditable);
        ApplicationManager.getApplication().invokeAndWait(() -> {
            TableCellRenderer centerRenderer = new TableViewRenderer();
            devServerTableComponent.setDefaultRenderer(Object.class, centerRenderer);
            devServerTableComponent.setModel(modelFile);
            devServerTableComponent.updateUI();
        });
    }

    /**
     * 获取表格模型
     * */
    public DevServerTableModel getTableModel() {
        return (DevServerTableModel) devServerTableComponent.getModel();
    }

    private DevServerTableModel getDefaultTableModel(String[] columnNames, JSONArray list, @NotNull Boolean isEditable) {
        DevServerTableModel defaultTableModel = new DevServerTableModel(columnNames, 0);
        if (CollectionUtil.isNotEmpty(list)) {
            list.forEach(model -> {
                JSONObject jsonObject = JSON.parseObject(model.toString());
                Vector<String> rowData = new Vector<>();
                for (String column : columnNames) {
                    String data = jsonObject.getString(column);
                    rowData.add(data);
                }
                defaultTableModel.addRow(rowData);
            });
        }
        defaultTableModel.setEditable(isEditable);
        return defaultTableModel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JBPanel();
        root.setLayout(new BorderLayout(0, 0));
        headComponent = new JBPanel();
        headComponent.setLayout(new BorderLayout(0, 0));
        headComponent.setMinimumSize(new Dimension(0, 30));
        headComponent.setPreferredSize(new Dimension(0, 30));
        root.add(headComponent, BorderLayout.NORTH);
        tableComponent = new JBPanel();
        tableComponent.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        root.add(tableComponent, BorderLayout.CENTER);
        final JBScrollPane scrollPane1 = new JBScrollPane();
        tableComponent.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        devServerTableComponent = new JBTable();
        scrollPane1.setViewportView(devServerTableComponent);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
