package com.tanghui.dev.idea.plugin.devserver.deploy.dialog;

import com.intellij.openapi.editor.Document;
import com.intellij.openapi.fileEditor.FileDocumentManager;
import com.intellij.openapi.fileTypes.FileType;
import com.intellij.openapi.fileTypes.FileTypeManager;
import com.intellij.openapi.project.Project;
import com.intellij.testFramework.LightVirtualFile;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBPanel;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ui.JBUI;
import com.tanghui.dev.idea.plugin.devserver.ui.HorizontalScrollBarEditor;
import lombok.Getter;
import lombok.Setter;

import javax.swing.JComponent;
import java.awt.*;

/**
 * @BelongsPackage: com.tanghuidev.idea.plugin.deploy.dialog
 * @Author: 唐煇
 * @CreateTime: 2026-01-20-15:51
 * @Description: 描述类的主要功能和用途。
 * @Version: v1.0
 */
@Getter
public class EditScript {
    private JBPanel<?> root;
    private JBLabel nameLabel;
    private final Project project;

    private HorizontalScrollBarEditor shellScriptEditor;
    @Setter
    private String content;
    @Setter
    private boolean edit = false;

    public EditScript(Project project, String name, String content) {
        this.project = project;
        $$$setupUI$$$();
        this.nameLabel.setText(name);
        this.shellScriptEditor.setText(content);
        this.content = content;

    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JBPanel();
        root.setLayout(new BorderLayout(0, 0));
        root.setMaximumSize(JBUI.size(700, 700));
        root.setMinimumSize(JBUI.size(700, 700));
        root.setPreferredSize(JBUI.size(700, 700));
        final JBPanel panel1 = new JBPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setMaximumSize(JBUI.size(2147483647, 40));
        panel1.setMinimumSize(JBUI.size(24, 40));
        panel1.setPreferredSize(JBUI.size(24, 40));
        root.add(panel1, BorderLayout.NORTH);
        final JBPanel panel2 = new JBPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        nameLabel = new JBLabel();
        nameLabel.setText("");
        panel2.add(nameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JBPanel panel3 = new JBPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        root.add(panel3, BorderLayout.CENTER);
        panel3.add(shellScriptEditor, BorderLayout.CENTER);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        String extension = "sh";
        FileType fileType = FileTypeManager.getInstance().getFileTypeByExtension(extension);
        // 使用 virtualFile 创建 Document（IDE 自动处理）
        Document document = FileDocumentManager.getInstance().getDocument(new LightVirtualFile("script.sh", fileType, ""));
        this.shellScriptEditor = new HorizontalScrollBarEditor(document, project, fileType, false, false);
    }
}
