package com.tanghui.dev.idea.plugin.devserver.ui.server.lastright;

import com.intellij.openapi.project.Project;
import com.intellij.ui.components.JBList;
import com.intellij.ui.components.JBPanel;
import com.intellij.ui.components.JBScrollPane;
import com.tanghui.dev.idea.plugin.devserver.data.model.ServerHostFileModel;
import lombok.Getter;

import javax.swing.*;
import java.awt.*;
import java.util.*;

@Getter
public class DirectoryListComponent {
    private JBPanel<?> root;
    private JBList<ServerHostFileModel> directoryList;
    private JBPanel<?> serverFileOperationToolbar;

    private final Project project;

    public DirectoryListComponent(Project project) {
        this.project = project;
        DefaultListModel<ServerHostFileModel> model = new DefaultListModel<>();
        directoryList.setModel(model);
        directoryList.setFixedCellHeight(36);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JBPanel();
        root.setLayout(new BorderLayout(0, 0));
        serverFileOperationToolbar = new JBPanel();
        serverFileOperationToolbar.setLayout(new BorderLayout(0, 0));
        serverFileOperationToolbar.setMinimumSize(new Dimension(0, 30));
        serverFileOperationToolbar.setPreferredSize(new Dimension(0, 30));
        root.add(serverFileOperationToolbar, BorderLayout.NORTH);
        final JBScrollPane jBScrollPane1 = new JBScrollPane();
        root.add(jBScrollPane1, BorderLayout.CENTER);
        directoryList = new JBList();
        directoryList.setEnabled(true);
        jBScrollPane1.setViewportView(directoryList);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
