package com.tanghui.dev.idea.plugin.devserver.ui.server.lastright;

import com.intellij.openapi.project.Project;
import com.intellij.ui.components.JBPanel;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.treeStructure.Tree;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.tanghui.dev.idea.plugin.devserver.renderer.ServerHostTreeCellRenderer;
import lombok.Getter;

import javax.swing.JComponent;
import java.awt.*;

@Getter
public class DirectoryTreeComponent {
    private JBPanel<?> root;
    private Tree serverDirectoryTree;

    private final Project project;

    public DirectoryTreeComponent(Project project) {
        this.project = project;
        serverDirectoryTree.setCellRenderer(new ServerHostTreeCellRenderer());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JBPanel();
        root.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        root.setMaximumSize(new Dimension(2147483647, 2147483647));
        root.setMinimumSize(new Dimension(300, 24));
        root.setPreferredSize(new Dimension(300, 24));
        final JBScrollPane jBScrollPane1 = new JBScrollPane();
        root.add(jBScrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        serverDirectoryTree = new Tree();
        serverDirectoryTree.setMinimumSize(new Dimension(0, 0));
        jBScrollPane1.setViewportView(serverDirectoryTree);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
