package com.tanghui.dev.idea.plugin.devserver.ui.server.lastright;

import com.intellij.openapi.editor.Document;
import com.intellij.openapi.fileEditor.FileDocumentManager;
import com.intellij.openapi.fileTypes.FileType;
import com.intellij.openapi.fileTypes.FileTypeManager;
import com.intellij.openapi.project.Project;
import com.intellij.psi.PsiDocumentManager;
import com.intellij.psi.PsiFile;
import com.intellij.psi.PsiFileFactory;
import com.intellij.testFramework.LightVirtualFile;
import com.intellij.ui.components.*;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.tanghui.dev.idea.plugin.devserver.deploy.dialog.EditScriptDialog;
import com.tanghui.dev.idea.plugin.devserver.icons.DevServerIcons;
import com.tanghui.dev.idea.plugin.devserver.ui.HorizontalScrollBarEditor;
import lombok.Getter;
import org.apache.commons.lang3.StringUtils;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;

@Getter
public class ExecuteRightComponent {
    private JBPanel<?> root;
    private JBTextField directoryTextField;
    private JBTextField userTextField;
    private JTextPane illustrateTextPane;
    private JButton editorButton;
    private HorizontalScrollBarEditor executeCommand;
    private OnOffButton scriptType;
    private JBLabel pathInfoLabel;

    private final Project project;

    public ExecuteRightComponent(Project project) {
        this.project = project;
        $$$setupUI$$$();
        this.scriptType.setOnText("脚本");
        this.scriptType.setOffText("命令");
        this.editorButton.setIcon(DevServerIcons.DevServer_TOOLBAR_UPDATE);
        this.editorButton.setBorder(null);
        this.editorButton.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String string = scriptType.isSelected() ? "脚本" : "命令";
                EditScriptDialog runShellScriptDialog = new EditScriptDialog(project, "执行" + string,
                        StringUtils.isNotBlank(executeCommand.getText().trim()) ? executeCommand.getText().trim() : "");
                runShellScriptDialog.setTitle("编辑执行" + string);
                runShellScriptDialog.showAndGet();
                if (runShellScriptDialog.getEditScript().isEdit()) {
                    String extension = "sh";
                    FileType fileType = FileTypeManager.getInstance().getFileTypeByExtension(extension);
                    // 使用 virtualFile 创建 Document（IDE 自动处理）
                    Document document = FileDocumentManager.getInstance().getDocument(new LightVirtualFile("script.sh", fileType, runShellScriptDialog.getContent()));
                    executeCommand.setDocument(document);
                    executeCommand.updateUI();
                }
            }
        });

    }

    public void createUIComponents() {
        FileType fileType = FileTypeManager.getInstance().getFileTypeByExtension("sh");
        PsiFile psiFile = PsiFileFactory.getInstance(project).createFileFromText("logeText.sh", fileType, "ll -a");
        Document document = PsiDocumentManager.getInstance(project).getDocument(psiFile);
        this.executeCommand = new HorizontalScrollBarEditor(document, project, fileType, false, false);
        this.executeCommand.setFont(new Font("Monaco", Font.BOLD, 14));
        this.executeCommand.updateUI();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JBPanel();
        root.setLayout(new BorderLayout(0, 0));
        final JBPanel panel1 = new JBPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 30, 0, 0), -1, -1));
        panel1.setMinimumSize(new Dimension(0, 30));
        panel1.setPreferredSize(new Dimension(0, 30));
        root.add(panel1, BorderLayout.NORTH);
        pathInfoLabel = new JBLabel();
        pathInfoLabel.setText("");
        panel1.add(pathInfoLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel2 = new JBPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        root.add(panel2, BorderLayout.CENTER);
        final JBPanel panel3 = new JBPanel();
        panel3.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setMaximumSize(new Dimension(2147483647, 80));
        panel3.setMinimumSize(new Dimension(24, 80));
        panel3.setPreferredSize(new Dimension(24, 80));
        panel2.add(panel3, BorderLayout.NORTH);
        final JBPanel panel4 = new JBPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel3.add(panel4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JBPanel panel5 = new JBPanel();
        panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel5.setMaximumSize(new Dimension(80, 2147483647));
        panel5.setMinimumSize(new Dimension(80, 24));
        panel5.setPreferredSize(new Dimension(80, 24));
        panel4.add(panel5, BorderLayout.WEST);
        final JLabel label1 = new JLabel();
        label1.setText("执行目录");
        panel5.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel6 = new JBPanel();
        panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel4.add(panel6, BorderLayout.CENTER);
        directoryTextField = new JBTextField();
        directoryTextField.setEditable(false);
        panel6.add(directoryTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JBPanel panel7 = new JBPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        panel3.add(panel7, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JBPanel panel8 = new JBPanel();
        panel8.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel8.setMaximumSize(new Dimension(80, 2147483647));
        panel8.setMinimumSize(new Dimension(80, 24));
        panel8.setPreferredSize(new Dimension(80, 24));
        panel7.add(panel8, BorderLayout.WEST);
        final JLabel label2 = new JLabel();
        label2.setText("执行用户");
        panel8.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JBPanel panel9 = new JBPanel();
        panel9.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel7.add(panel9, BorderLayout.CENTER);
        userTextField = new JBTextField();
        userTextField.setEditable(false);
        panel9.add(userTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JBPanel panel10 = new JBPanel();
        panel10.setLayout(new BorderLayout(0, 0));
        panel2.add(panel10, BorderLayout.CENTER);
        final JBPanel panel11 = new JBPanel();
        panel11.setLayout(new GridLayoutManager(1, 1, new Insets(10, 20, 10, 20), -1, -1));
        panel11.setMaximumSize(new Dimension(2147483647, 300));
        panel11.setMinimumSize(new Dimension(24, 100));
        panel11.setPreferredSize(new Dimension(24, 100));
        panel10.add(panel11, BorderLayout.NORTH);
        final JBScrollPane jBScrollPane1 = new JBScrollPane();
        panel11.add(jBScrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        jBScrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), "执行说明", TitledBorder.LEFT, TitledBorder.ABOVE_TOP, null, null));
        illustrateTextPane = new JTextPane();
        jBScrollPane1.setViewportView(illustrateTextPane);
        final JBPanel panel12 = new JBPanel();
        panel12.setLayout(new BorderLayout(0, 0));
        panel10.add(panel12, BorderLayout.CENTER);
        final JBPanel panel13 = new JBPanel();
        panel13.setLayout(new BorderLayout(0, 0));
        panel13.setMaximumSize(new Dimension(2147483647, 35));
        panel13.setMinimumSize(new Dimension(24, 35));
        panel13.setPreferredSize(new Dimension(24, 35));
        panel12.add(panel13, BorderLayout.NORTH);
        final JBPanel panel14 = new JBPanel();
        panel14.setLayout(new GridLayoutManager(1, 1, new Insets(0, 20, 0, 10), -1, -1));
        panel13.add(panel14, BorderLayout.WEST);
        scriptType = new OnOffButton();
        panel14.add(scriptType, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 25), new Dimension(-1, 25), new Dimension(-1, 25), 0, false));
        final JBPanel panel15 = new JBPanel();
        panel15.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel15.setMaximumSize(new Dimension(35, 2147483647));
        panel15.setMinimumSize(new Dimension(35, 24));
        panel15.setPreferredSize(new Dimension(35, 24));
        panel13.add(panel15, BorderLayout.EAST);
        editorButton = new JButton();
        editorButton.setAutoscrolls(true);
        editorButton.setText("");
        panel15.add(editorButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(30, 30), new Dimension(30, 30), new Dimension(30, 30), 0, false));
        final JBPanel panel16 = new JBPanel();
        panel16.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel13.add(panel16, BorderLayout.CENTER);
        final JBPanel panel17 = new JBPanel();
        panel17.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel12.add(panel17, BorderLayout.CENTER);
        panel17.add(executeCommand, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
