package com.tanghui.dev.idea.plugin.devserver.ui.server.lastright;

import com.intellij.openapi.project.Project;
import com.intellij.ui.components.JBPanel;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.treeStructure.Tree;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Getter;

import javax.swing.JComponent;
import javax.swing.tree.TreeSelectionModel;
import java.awt.*;
import java.util.*;


@Getter
public class ExecuteLeftComponent {
    private JBPanel<?> root;
    private Tree commandTree;
    private JBPanel<?> commandToolbar;
    private final Project project;

    public ExecuteLeftComponent(Project project) {
        this.project = project;
        // 设置只能单选
        this.commandTree.getSelectionModel().setSelectionMode(
                TreeSelectionModel.SINGLE_TREE_SELECTION
        );
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JBPanel();
        root.setLayout(new BorderLayout(0, 0));
        root.setMinimumSize(new Dimension(300, 0));
        root.setPreferredSize(new Dimension(300, 0));
        commandToolbar = new JBPanel();
        commandToolbar.setLayout(new BorderLayout(0, 0));
        commandToolbar.setMinimumSize(new Dimension(24, 30));
        commandToolbar.setPreferredSize(new Dimension(24, 30));
        root.add(commandToolbar, BorderLayout.NORTH);
        final JBPanel panel1 = new JBPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        root.add(panel1, BorderLayout.CENTER);
        final JBScrollPane jBScrollPane1 = new JBScrollPane();
        panel1.add(jBScrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        commandTree = new Tree();
        jBScrollPane1.setViewportView(commandTree);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
